# Generated by Django 2.0 on 2020-03-29 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
