# Generated by Django 2.0 on 2020-03-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0003_corren'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corren_euro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euro', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='corren',
            name='euro',
        ),
    ]
